[package]
name = "moat_server"
version = "0.1.0"
authors = ["Kafva <https://github.com/Kafva>"]
edition = "2021"

[dependencies]
actix-web = "4"
clap =   { version = "3.1.12",     features = ["derive"] }
rusqlite = { version = "0.28.0",   features = ["bundled"] }
base64 = "0.13.0"
