# Use `ROCKET_ENV` to modify which configuration is used
# Defaults for _all_ profiles
[default]
address = "0.0.0.0"
port = 7654
limits = { forms = "64 kB", json = "1 MiB" }
keep_alive = 5
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true

[default.tls]
# TLS requires an addition in the Cargo.toml configuration
certs = "./ssl/moat_server.crt"
key = "./ssl/moat_server.key"