[package]
name = "remoat_server"
version = "0.1.0"
authors = ["Kafva <Martensson.Jonas98@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
rusqlite = "0.25.3"
chrono = "0.4"
clap = "3.0.0-beta.2"
